[".local/share/asdf"]
type = "git-repo"
url = "https://github.com/asdf-vm/asdf.git"
refreshPeriod = "168h"
[".local/share/asdf".clone]
args = ["--branch", "v0.10.2"]
[".local/share/asdf".pull]
args = ["origin", "v0.10.2"]
