#!/bin/bash

# Installation
echo "# Installing pipx"
python3 -m pip install --user pipx
python3 -m pipx ensurepath

# Installing pre-commit
pipx install pre-commit
pipx inject pre-commit gitlint-core

# Installing protonup
sudo apt install gamemode
#pipx install protonup
pipx install protonup-ng
protonup -d $HOME/.steam/steam/compatibilitytools.d/
