#!/bin/bash

. $HOME/.bashrc

# Install Neovim
echo "# Installing Neovim"
wget2 -O $HOME/.local/bin/nvim https://github.com/neovim/neovim/releases/download/v0.9.0/nvim.appimage
chmod u+x $HOME/.local/bin/nvim

# Install LunarVim
echo "# Installing LunarVim"
LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh) --no-install-dependencies
