#!/bin/bash
# Install python build dependencies
echo "# Install python build dependencies"
sudo apt update && sudo apt install build-essential libssl-dev zlib1g-dev \
	libbz2-dev libreadline-dev libsqlite3-dev curl git \
	libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

# Install mise
echo "# Install mise"
curl https://mise.run | sh
eval "$($HOME/.local/bin/mise activate bash --shims)"
mise settings set experimental true
mise use --global -y node@latest python@latest java@temurin rust@latest zoxide@latest eza@latest lazygit@latest cargo:tree-sitter-cli@latest
rustup component add rust-analyzer
mise settings set experimental false
