#!/bin/bash

# nushell
## Install nushell
echo "# Installing nushell"
curl -fsSL https://apt.fury.io/nushell/gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/fury-nushell.gpg
echo "deb https://apt.fury.io/nushell/ /" | sudo tee /etc/apt/sources.list.d/fury.list
sudo apt update
sudo apt install nushell

nu --commands "mkdir (\$nu.data-dir | path join 'vendor/autoload')"
nu --commands "^mise activate nu | save --force (\$nu.data-dir | path join 'vendor/autoload/mise.nu')"
nu --commands "^atuin init nu | save --force (\$nu.data-dir | path join 'vendor/autoload/atuin.nu')"
nu --commands "^zoxide init nushell --cmd cd | save --force (\$nu.data-dir | path join 'vendor/autoload/zoxide.nu')"
