#!/bin/bash

# Z shell
## Install Z shell packages and documentation
echo "# Installing Z shell"
sudo apt install -y zsh zsh-doc

## Install zplug
if [ ! -d ~/.zplug/ ]; then
	wget2 -qO- https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
fi

## Change default shell to Z shell
if ! command -v zsh &> /dev/null; then
	chsh -s $(command -v zsh)
fi
