#!/bin/bash

# Starship prompt
#& Install Starship Binary
echo "# Installing Starship prompt"
sh -c "$(curl -fsLS https://starship.rs/install.sh)" -- -y --bin-dir ~/.local/bin

# Z shell
## Install Z shell packages and documentation
echo "# Installing Z shell"
sudo apt install -y zsh zsh-doc fzf ripgrep

## Change default shell to Z shell
if ! command -v zsh &> /dev/null; then
	chsh -s $(command -v zsh)
fi
