#!/bin/bash

# Install Neovim
echo "# Installing Neovim"
wget2 -O $HOME/.local/bin/nvim https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x $HOME/.local/bin/nvim

# Install LunarVim
echo "# Installing LunarVim"
bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
