#!/bin/bash

# Install mise
echo "# Install mise"
curl https://mise.run | sh
eval "$($HOME/.local/bin/mise activate bash --shims)"
mise settings set experimental true
mise use --global -y node@latest python@latest rust@latest java@temurin-20 zoxide@latest eza@latest lazygit@latest cargo:tree-sitter-cli@latest
mise settings set experimental false
