#!/bin/bash

. ${ASDF_DATA_DIR:-$HOME/.local/share/asdf}/asdf.sh

# Install Development Environments
## Direnv
echo "# Installing Direnv Plugin Dependencies"
sudo apt install -y curl git direnv

echo "# Installing Direnv Plugin"
asdf plugin-add direnv
asdf direnv setup --shell bash --version system
asdf direnv setup --shell zsh --version system
direnv allow $HOME/.envrc

## Node.js
echo "# Installing Node.js Plugin Dependencies"
sudo apt install -y dirmngr gpg curl gawk

echo "# Installing Node.js Plugin"
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git

echo "# Installing Latest Node.js"
asdf install nodejs latest
asdf global nodejs latest

## Python
echo "# Installing Python Plugin Dependencies"
sudo apt install -y make build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

echo "# Installing Python Plugin"
asdf plugin-add python

echo "# Installing Latest Python"
asdf install python latest
asdf global python latest

## Rust
echo "# Installing Rust Plugin"
asdf plugin-add rust https://github.com/code-lever/asdf-rust.git

echo "# Installing Latest Stable Rust"
asdf install rust latest
asdf global rust latest

## zoxide
echo "# Installing zoxide Plugin"
asdf plugin add zoxide https://github.com/nyrst/asdf-zoxide.git

echo "# Installing Latest zoxide"
asdf install zoxide latest
asdf global zoxide latest

## exa
echo " Installing exa Plugin"
asdf plugin add exa https://github.com/nyrst/asdf-exa.git

echo "Installing Latest exa"
asdf install exa latest
asdf global exa latest
