#!/bin/bash

# Install kitty
echo "# Installing kitty"
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n

# Symlink into $PATH
ln -s ~/.local/kitty.app/bin/kitty ~/.local/bin/

# Add Desktop shortcut
cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/

# Download Alternative Icon
wget2 -O ~/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty_alt.png https://github.com/hristost/kitty-alternative-icon/raw/main/kitty_icon.png
# Add Desktop icon
sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty_alt.png|g" \
  ~/.local/share/applications/kitty.desktop
