#!/bin/bash

# Z shell
## Install Z shell packages and documentation
echo "# Installing Z shell"
sudo apt install -y zsh zsh-doc fzf ripgrep

## Change default shell to Z shell
if ! command -v zsh &> /dev/null; then
	chsh -s $(command -v zsh)
fi
